#!/bin/bash
# 10-populate-home

# Create a user/group for local development.
chroot $target groupadd -g 1000 jordif
chroot $target useradd -m -s /bin/bash -g jordif -G sudo -u 1000 jordif

# /root is already copied on another script (scripts/FAIBASE/10-misc)
# Our local user can ssh as root.
fcopy -Uv /root/.ssh/authorized_keys -m root,root,600
chmod 700 $target/root/.ssh/
chmod 600 $target/root/.ssh/authorized_keys

# Deploy authorized_keys, owner jordif, rw-------
fcopy -ir /home/jordif/
chmod 700 $target/home/jordif/.ssh/
chmod 600 $target/home/jordif/.ssh/authorized_keys
chown -R 1000:1000 $target/home/jordif/

