#! /bin/bash

# assign classes hosts

# use a list of classes for our demo machine
case $HOSTNAME in
    faiserver)
        echo "FAIBASE DEMO FAISERVER" ;;
    demohost)
        echo "FAIBASE DHCPC DEMO" ;;
    faitest)
        echo "FAIBASE KVM" ;;
    toluca)
        echo "FAIBASE VMWARE" ;;
    *)
        echo "FAIBASE" ;;
esac

(ifclass I386 || ifclass AMD64) && echo GRUB 
exit 0
